name: Test Package Action

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Joomla Packager Action (Package)
        uses: N6REJ/joomla-packager@2025.6.23
        with:
          extension-name: 'pkg_testpackage'
          extension-xml: 'test-extensions/test-package/pkg_testpackage.xml'
          extension-type: 'package'
