name: Test Component Action

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Joomla Packager Action (Component)
        uses: N6REJ/joomla-packager@2025.6.23
        with:
          extension-name: 'com_testcomponent'
          extension-xml: 'test-extensions/test-component/com_testcomponent.xml'
          extension-type: 'component'
